spring:
  datasource:
    username: root
    password: root
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    hikari:
      maximum-pool-size: 25
      minimum-idle: 1
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 8081

grpc:
  client:
    UserService:
      address: static://localhost:9090
      negotiation-type: PLAINTEXT
